In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [39]:
data=pd.read_csv('F:/Python Programs/DataSets/creditcard.csv')

In [40]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [41]:
#backward elimination----
import statsmodels.regression.linear_model as sm
ones=[1 for i in range(0,len(data['Time']))]
ones=pd.DataFrame(ones)
data.insert(0,'ones',ones)

In [42]:
x_opt=data.iloc[:,0:len(data.columns)-1].copy()
temp=[i for i in range(0,len(data.columns)-1)]
x_opt.columns=(temp)

In [43]:
col_names={}
for i in range(0,len(x_opt.columns)):
    col_names[i]=data.columns[i]

In [44]:
x_opt.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,1,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,1,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,1,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,1,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99

In [45]:
ols = sm.OLS(endog = data['Class'], exog = x_opt).fit() 
print(ols.summary() )

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Class   R-squared:                       0.522
Model:                            OLS   Adj. R-squared:                  0.522
Method:                 Least Squares   F-statistic:                 1.035e+04
Date:                Tue, 02 Jun 2020   Prob (F-statistic):               0.00
Time:                        17:44:58   Log-Likelihood:             6.0697e+05
No. Observations:              284807   AIC:                        -1.214e+06
Df Residuals:                  284776   BIC:                        -1.214e+06
Df Model:                          30
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
0              0.0015      0.000      8.863      0.000       0.001       0.002
1          -4.394e-09   1.55e-09     -2.828      0.005   -7.44e-09   -1.35e-09
2             -0.0019   3.53e-05    -54.609      0.000      -0.002      -0.002
3              0.0029   6.85e-05     41.857      0.000       0.003       0.003
4             -0.0051   4.86e-05   -104.742      0.000      -0.005      -0.005
5              0.0038   4.06e-05     93.064      0.000       0.004       0.004
6             -0.0023   6.59e-05    -35.359      0.000      -0.002      -0.002
7             -0.0017   5.06e-05    -32.772      0.000      -0.002      -0.002
8             -0.0068   7.45e-05    -91.930      0.000      -0.007      -0.007
9              0.0008   4.79e-05     17.496      0.000       0.001       0.001
10            -0.0036   4.96e-05    -73.105      0.000      -0.004      -0.004
11            -0.0081   5.25e-05   -154.391      0.000      -0.008      -0.008
12             0.0063   5.57e-05    112.238      0.000       0.006       0.006
13            -0.0108   5.47e-05   -197.322      0.000      -0.011      -0.011
14            -0.0002   5.43e-05     -3.940      0.000      -0.000      -0.000
15            -0.0132    5.7e-05   -231.281      0.000      -0.013      -0.013
16            -0.0002   6.06e-05     -3.754      0.000      -0.000      -0.000
17            -0.0093   6.14e-05   -151.433      0.000      -0.009      -0.009
18            -0.0160   6.37e-05   -251.089      0.000      -0.016      -0.016
19            -0.0056   6.52e-05    -85.533      0.000      -0.006      -0.005
20             0.0019   6.74e-05     28.258      0.000       0.002       0.002
21             0.0003      0.000      2.611      0.009    7.04e-05       0.000
22             0.0020   7.82e-05     26.070      0.000       0.002       0.002
23             0.0002   7.74e-05      3.191      0.001    9.52e-05       0.000
24             0.0002   9.28e-05      1.731      0.083   -2.12e-05       0.000
25            -0.0005   8.89e-05     -5.803      0.000      -0.001      -0.000
26             0.0003      0.000      3.043      0.002       0.000       0.001
27             0.0004      0.000      3.378      0.001       0.000       0.001
28             0.0017      0.000     12.525      0.000       0.001       0.002
29             0.0011      0.000      6.976      0.000       0.001       0.001
30          7.139e-06   7.49e-07      9.531      0.000    5.67e-06    8.61e-06
==============================================================================
Omnibus:                   596317.004   Durbin-Watson:                   1.971
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       8572253636.654
Skew:                          17.562   Prob(JB):                         0.00
Kurtosis:                     852.193   Cond. No.                     3.90e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.9e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [46]:
#remove 24th col---
temp=[i for i in range(0,len(x_opt.columns)) if i!=24]

In [51]:
#x_opt=x_opt.iloc[:,temp]
ols = sm.OLS(endog = data['Class'], exog = x_opt).fit() 
print(ols.summary() )

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Class   R-squared:                       0.522
Model:                            OLS   Adj. R-squared:                  0.522
Method:                 Least Squares   F-statistic:                 1.071e+04
Date:                Tue, 02 Jun 2020   Prob (F-statistic):               0.00
Time:                        17:48:53   Log-Likelihood:             6.0697e+05
No. Observations:              284807   AIC:                        -1.214e+06
Df Residuals:                  284777   BIC:                        -1.214e+06
Df Model:                          29
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
ones           0.0015      0.000      9.049      0.000       0.001       0.002
Time       -4.228e-09   1.55e-09     -2.726      0.006   -7.27e-09   -1.19e-09
V1            -0.0019   3.44e-05    -56.554      0.000      -0.002      -0.002
V2             0.0028   6.49e-05     43.589      0.000       0.003       0.003
V3            -0.0051   4.79e-05   -106.564      0.000      -0.005      -0.005
V4             0.0038   4.02e-05     94.025      0.000       0.004       0.004
V5            -0.0024   6.29e-05    -37.582      0.000      -0.002      -0.002
V6            -0.0016   4.94e-05    -33.219      0.000      -0.002      -0.002
V7            -0.0068   7.13e-05    -95.526      0.000      -0.007      -0.007
V8             0.0008   4.76e-05     17.413      0.000       0.001       0.001
V9            -0.0036   4.95e-05    -73.309      0.000      -0.004      -0.004
V10           -0.0081   5.21e-05   -155.798      0.000      -0.008      -0.008
V11            0.0063   5.57e-05    112.295      0.000       0.006       0.006
V12           -0.0108   5.47e-05   -197.409      0.000      -0.011      -0.011
V13           -0.0002   5.43e-05     -3.919      0.000      -0.000      -0.000
V14           -0.0132    5.7e-05   -231.486      0.000      -0.013      -0.013
V15           -0.0002   6.06e-05     -3.734      0.000      -0.000      -0.000
V16           -0.0093   6.14e-05   -151.446      0.000      -0.009      -0.009
V17           -0.0160   6.37e-05   -251.091      0.000      -0.016      -0.016
V18           -0.0056   6.52e-05    -85.527      0.000      -0.006      -0.005
V19            0.0019   6.72e-05     28.206      0.000       0.002       0.002
V20            0.0003      0.000      3.225      0.001       0.000       0.001
V21            0.0021   7.77e-05     26.479      0.000       0.002       0.002
V22            0.0002   7.71e-05      3.047      0.002    8.38e-05       0.000
V24           -0.0005   8.89e-05     -5.789      0.000      -0.001      -0.000
V25            0.0003      0.000      2.978      0.003       0.000       0.001
V26            0.0004      0.000      3.377      0.001       0.000       0.001
V27            0.0017      0.000     12.597      0.000       0.001       0.002
V28            0.0011      0.000      7.000      0.000       0.001       0.001
Amount      6.667e-06   6.98e-07      9.556      0.000     5.3e-06    8.03e-06
==============================================================================
Omnibus:                   596297.193   Durbin-Watson:                   1.971
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       8572986367.911
Skew:                          17.561   Prob(JB):                         0.00
Kurtosis:                     852.230   Cond. No.                     3.79e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.79e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [48]:
x_opt.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,25,26,27,28,29,30
0,1,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,...,0.403993,0.251412,-0.018307,0.277838,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,...,-0.145783,-0.069083,-0.225775,-0.638672,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,1,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,...,-2.261857,0.524980,0.247998,0.771679,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,1,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,...,-1.232622,-0.208038,-0.108300,0.005274,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,1,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,...,0.803487,0.408542,-0.009431,0.798278,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99

In [49]:
for i in x_opt.columns:
    if col_names.get(i):
        x_opt.rename(columns={i:col_names[i]},inplace=True)

In [50]:
x_opt.head()

,ones,Time,V1,V2,V3,V4,V5,V6,V7,V8,...,V19,V20,V21,V22,V24,V25,V26,V27,V28,Amount
0,1,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,...,0.403993,0.251412,-0.018307,0.277838,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,...,-0.145783,-0.069083,-0.225775,-0.638672,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,1,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,...,-2.261857,0.524980,0.247998,0.771679,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,1,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,...,-1.232622,-0.208038,-0.108300,0.005274,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,1,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,...,0.803487,0.408542,-0.009431,0.798278,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [53]:
features=x_opt.iloc[:,:]
label=data['Class']
x_train,x_test,y_train,y_test=train_test_split(features,label,test_size=0.2,random_state=0)

classifier=KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_train,y_train)
pred=classifier.predict(x_test)

print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[56859     2]
 [   93     8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.80      0.08      0.14       101

    accuracy                           1.00     56962
   macro avg       0.90      0.54      0.57     56962
weighted avg       1.00      1.00      1.00     56962

In [54]:
features=x_opt.iloc[:,:]
label=data['Class']
x_train,x_test,y_train,y_test=train_test_split(features,label,test_size=0.2,random_state=0)

classifier=GaussianNB()
classifier.fit(x_train,y_train)
pred=classifier.predict(x_test)

print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[56487   374]
 [   39    62]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     56861
           1       0.14      0.61      0.23       101

    accuracy                           0.99     56962
   macro avg       0.57      0.80      0.61     56962
weighted avg       1.00      0.99      1.00     56962

In [55]:
features=x_opt.iloc[:,:]
label=data['Class']
x_train,x_test,y_train,y_test=train_test_split(features,label,test_size=0.2,random_state=0)

classifier=DecisionTreeClassifier()
classifier.fit(x_train,y_train)
pred=classifier.predict(x_test)

print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[56839    22]
 [   25    76]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.78      0.75      0.76       101

    accuracy                           1.00     56962
   macro avg       0.89      0.88      0.88     56962
weighted avg       1.00      1.00      1.00     56962